klasy = {"2lIB" : "-49",
		"3lIB" : "-23",
		"2Gaa" : "-1",
		"2Gbb" : "-2",
		"2Gmm" : "-3",
		"3Gaa" : "-4",
		"3Gbb" : "-5",
		"3Gmm" : "-6",
		"1Lhh" : "-50",
		"1bb" : "-51",
		"1Lcc" : "-52",
		"1 Lee" : "*12",
		"1Lmm" : "-53",
		"1Lpp" : "-54",
		"1Lyy" : "-55",
		"1Lzz" : "-56",
		"2Lee" : "-10",
		"2Lpp" : "-11",
		"2Lhh" : "-12",
		"2Lbb" : "-13",
		"2Lcc" : "-14",
		"2Lmm" : "-15",
		"3Laa" : "-18",
		"3Lcc" : "-19",
		"3Lbb" : "-20",
		"3Lmm" : "-21",
		"3Lpp" : "-22",
		"x1i.Gnyp, K" : "*28",
		"5l.CAS" : "*29",
		"5l.KORIB" : "*30",
		"7L.bilans" : "*31",
		"KORIBbilas" : "*32",
		"#ITN" : "*33",
		"xx3Lah" : "*34",
		"Uczniowskie koło biologiczne" : "*35",
		"xczytelnia" : "*36",
		"xinternat" : "*37",
		"XX-" : "*38",
		"konsultacje" : "*39",
		"zaj in rr" : "*40",
		"x1pp" : "*41",
		"SKS" : "*42",
		"Internat" : "*43",
		"\\*/ koło" : "*44",
		"yzdolni z pom" : "*45",
		"ITN" : "*46",
		"MYPzebranie" : "*47",
		"internat" : "*48",
		"DYS" : "*49",
		"śmie" : "*50",
		"18" : "*51",
		"DOM MARZEŃ" : "*52",
		"wójcik" : "*53",
		"DYRZ" : "*54",
		"Zdolni z  pomorza" : "*55"}


nauczyciele = {'Bożena Budkiewicz' : '-1',
				'Adam Gmyrek' : '-3',
				'Justyna Horodecka-Nowicka' : '-4',
				'Urszula Praska' : '-5',
				'Agata Taźbierska' : '-6',
				'Marta Bielak-Bodnar' : '-7',
				'Olga Wrońska' : '-8',
				'Anna Gwiazda' : '-9',
				'Elżbieta Strach' : '-10',
				'Anna Trelińska' : '-135',
				'Krzysztof Bartczak' : '-12',
				'Dorota Dźwig' : '-13',
				'Joanna Jankowska' : '-14',
				'Dorota Wnuczyńska' : '-15',
				'Leszek Buczyński' : '-16',
				'Małgorzata Aszendorf' : '-17',
				'Marta Burzyńska' : '-18',
				'Agnieszka Czepulonis' : '-19',
				'Anna Czarnowska' : '-20',
				'Teresa Ćwiklak' : '-21',
				'Magdalena Fiałkowska-Smiatacz' : '-22',
				'Renata Fiałkowska' : '-23',
				'Joanna Goździewicz' : '-24',
				'Zofia Krakowiak-Michlewicz' : '-25',
				'Joanna Nowak' : '-26',
				'Aleksandra Przekowiak' : '-27',
				'Magdalena Roda' : '-28',
				'Marta Smalara-Lewandowska' : '-29',
				'Sława Winiarska-Mielniczuk' : '-30',
				'Andrzej Wojniusz' : '-31',
				'Joanna Artwińska' : '-32',
				'Zbigniew Kruszewski' : '-33',
				'Magdalena Lotterhoff' : '-34',
				'Iwona Łapińska' : '-35',
				'Brygida Maciejewska' : '-36',
				'Małgorzata Meronk' : '-37',
				'Ewa Niwińska-Lipińska' : '-38',
				'Ewa Prylińska' : '-39',
				'Joanna Rybicka' : '-40',
				'Joanna Sadowska' : '-41',
				'Celina Bujalska' : '-62',
				'Anna Czernihowska-Tymoszyk' : '-63',
				'Magdalena Łozowicka-Honkisz' : '-64',
				'Dariusz Piasek' : '-65',
				'Iwona Walendziak' : '-66',
				'Danuta Bussler' : '-42',
				'Małgorzata Kupczyk-Skodowska' : '-44',
				'Alicja .Nowak' : '-45',
				'Marta Rogocka' : '-46',
				'Katarzyna Radzikowska' : '-142',
				'Katarzyna Lewańczyk' : '-139',
				'Adam Dzedzej' : '-73',
				'Janina Filipowicz' : '-74',
				'Małgorzata Ilewicz' : '-75',
				'Anna Kierznikowicz' : '-76',
				'Jacek Lech' : '-77',
				'Katarzyna Łuczyńska' : '-78',
				'Grażyna Miłosz' : '-79',
				'Agnieszka Orzeszek' : '-80',
				'Anita Pawłowska' : '-81',
				'Agnieszka Skalska' : '-82',
				'Sylwia Tarała' : '-83',
				'Wojciech Tomalczyk' : '-84',
				'Witold Zakrzacki' : '-85',
				'Irmina Kulik' : '-47',
				'Elżbieta Kwella' : '-48',
				'Justyna Raulin' : '-49',
				'Danuta Sadaj' : '-50',
				'Daria Świderska' : '-51',
				'Artur Kolincio' : '-52',
				'Elżbieta Koziróg' : '-53',
				'Marta Mąkosa' : '-54',
				'Emilia Przybysz' : '-55',
				'Włodzimierz Subczyński' : '-56',
				'Karolina Hłasko' : '-57',
				'Wiesław Kosakowski' : '-58',
				'Iwona Kotowska' : '-59',
				'Waldemar Kotowski' : '-60',
				'Małgorzata Kubik' : '-61',
				'Konrad Buzak' : '-67',
				'Bożena Rzeszowska' : '-69',
				'Ryszard Szubartowski' : '-70',
				'Joanna Śmierzchalska' : '-71',
				'Jacek Górski' : '-88',
				'Grzegorz Henicz' : '-89',
				'Anna Konieczna' : '-90',
				'Katarzyna Łończuk' : '-91',
				'Aleksandra Ogiegło' : '-92',
				'Małgorzata Szymańska-Pancewicz' : '-93',
				'Bożena Orłowska' : '-143',
				'Grzegorz Urgacz' : '-95',
				'Michał Koss' : '-96',
				'Małgorzata Olszowa' : '-97',
				'Michał Szczyptański' : '-99',
				'Anna Duszak' : '-100',
				'Bożena Chmielińska' : '-101',
				'Anna Rzepa' : '-138',
				'Dorota Stepaniuk' : '-152',
				'Alicja Krzemieniewska' : '-126',
				'Joanna Rozkwitalska' : '-102',
				' M' : '*101',
				'Antoni Augustynowicz' : '-86',
				'Artur Toeplitz' : '-104',
				' Talent1' : '-107',
				' Talent2' : '-108',
				'ww geokot' : '-109',
				'Marta Kwaśnik' : '-110',
				'Natalia Kur' : '-111',
				'Maciej Langowski' : '-112',
				'Arkadiusz Piąsta' : '-113',
				'Dagmara Wierzbicka' : '-2',
				'Brygida Pacuła' : '-115',
				'koło Rozkwitalska' : '-116',
				' Koło biologiczne' : '-118',
				'Radosław Grabicki' : '-119',
				'Monika Pajączkowska' : '-120',
				' ITN-samodzielna praca uczniów' : '-122',
				'Zuzanna Od Konieczna' : '-123',
				'-- --' : '-127',
				' Nasz Dom' : '-128',
				' Graman, Alaksandra' : '-130',
				'Piotr Zatorski' : '-131',
				' 3GBMAD' : '-132',
				'Bożena Teofilewska' : '-140',
				'Marzena Szczurowska' : '-141',
				' rezerwa' : '-145',
				'Przemysław Rojewski' : '-153',
				'P Wołodko' : '-154',}

dzwonki = ["7<sup>45</sup> - 8<sup>30</sup",
			"8<sup>40</sup> - 9<sup>25</sup",
			"9<sup>35</sup> - 10<sup>20</sup",
			"10<sup>30</sup> - 11<sup>15</sup",
			"11<sup>25</sup> - 12<sup>10</sup",
			"12<sup>30</sup> - 13<sup>15</sup",
			"13<sup>25</sup> - 14<sup>10</sup",
			"14<sup>25</sup> - 15<sup>10</sup",
			"15<sup>15</sup> - 16<sup>00</sup",
			"16<sup>05</sup> - 16<sup>50</sup",
			#"16<sup>55</sup> - 17<sup>40</sup",
			#"17<sup>45</sup> - 18<sup>30</sup",
			]
